PonyWeb/urls.py
from django.conf.urls import include, url, i18n
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include(i18n)),
    url(r'^', include('pw.urls')),
]

pw/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^login', views.log_in),
    url(r'^signup', views.signup),
    url(r'^logout', views.log_out),
    url(r'^tos', TemplateView.as_view(template_name="tos.djhtml")),
    url(r'^account/$', views.account),
    url(r'^account/(?P<username>[A-Za-z_][A-Za-z0-9_]+)', views.view_account),
    url(r'^account/(?P<id_user>[0-9]+)', views.view_account),
    # API
    url(r'^api/', include('pw.api_urls')),
    # News
    url(r'^news/$', views.news),
    url(r'^news/subscriptions$', views.subscriptions),
    url(r'^news/write$', views.write_news),
    url(r'^news/(?P<id>[0-9]+)', views.view_news)
]

pw/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=30)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

class SignupForm(UserCreationForm):
    email = forms.EmailField(label="Email address")
    gender = forms.CharField()

class ModifyAccountForm(forms.Form):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    gender = forms.CharField(required=False)
    twitter = forms.CharField(required=False)
    new_password = forms.CharField(required=False)
    new_password2= forms.CharField(required=False)
    password     = forms.CharField(required=True)

class NewNewsForm(forms.Form):
    title = forms.CharField(max_length=200)
    content = forms.CharField()

templates/article.html
{% extends 'base.html' %}
{% load static %}
{% block title %} News {% endblock %}
{% block style %}
  <style>
   .articles {
     margin-left: 10px;
     margin-right: 10px;
   };
   .right {
     float: right;
   }
  </style>
{% endblock %}
{% block activenews %}active{% endblock %}
{% block content %}
  <div class="articles segment">
    <h2 class="large header">{{ item.title }}</h2>
    {% autoescape off %}
    <p>{{ item.summary }}</p>
    {% endautoescape %}
  </div>
{% endblock %}

templates/base.html
{% load i18n %}
<html {% block app %}{% endblock %}>
	<head><title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="/dist/semantic.min.css">
		<link rel="stylesheet" href="/dist/base.css">
		<meta name=viewport content="width=device-width, initial-scale=1">
		<meta name="mobile-web-app-capable" content="yes">
		<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js"></script>
		{% block style %} {% endblock %}
		{% block scripthead %} {% endblock %}
	</head>
	<body>
		<div class="ui main pointing menu">
			<div class="header item">
				PonyWeb
			</div>
			<a class="{%if mode == "home"%}active{%endif%} item" {%if mode != "home"%}href="{%url 'pw.views.home'%}"{%endif%}>
				<i class="home icon"></i>{% trans "Home" %}
			</a>
			<a class="{%if mode == "news"%}active{%endif%} item" {%if mode != "news"%}href="{%url 'pw.views.news'%}"{%endif%}>
				<i class="newspaper icon"></i>{% trans "Blog posts" %}
			</a>
			<a class="{% if mode == "pictures" %}active{% endif %} item">
				<i class="camera retro icon"></i>{% trans "Pictures" %}
			</a>
			<a class="{% if mode == "stories" %}active{% endif %} item">
				<i class="book icon"></i>{% trans "Stories" %}
			</a>
			<a class="{% if mode == "music" %}active{% endif %} item">
				<i class="sound icon"></i>{% trans "Music" %}
			</a>
			{% block addmenu %} {% endblock %}
			<div class="menu right">
				{% if not user.is_authenticated %}
					<a class="{% if mode == "login" %}active{% endif %} item" {% if mode != "login" %}href="{% url 'pw.views.log_in' %}"{% endif %}>
						Log in
					</a>
					<a class="{% if mode == "signup"%}active{% endif %} item" {% if mode != "signup"%}href="{% url 'pw.views.signup'%}"{% endif %}>
						Sign up
					</a>
				{% else %}
					<a class="item right" href="{% url 'pw.views.log_out' %}">
						Log out
					</a>
					<a class="{%if mode == "account"%}active{%endif%} item" {% if mode != "account" %}href="{%url 'pw.views.account' %}"{% endif %}>
						Edit my Profile
					</a>
					<a class="{%if mode == "self"%}active{%endif%} item" {%if mode != "self"%}href="{% url 'pw.views.view_account' request.user.username %}"{%endif%}>
						My Profile
					</a>
				{% endif %}
			</div>
		</div>
		<div class="ui grid">
			{% block secondarymenu %}
			{% endblock %}
			<div class="row padding-reset">
				<div class="column">
					{% block content %}

					{% endblock %}
				</div>
			</div>
		</div>
		<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
		<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
		<script src="/dist/semantic.min.js"></script>
		{% block script %} {% endblock %}
	</body>
</html>

templates/blogindex.html
{% extends 'base.html' %}
{% load static %}
{% block title %} News {% endblock %}
{% block style %}
  <style>
   .articles {
     margin-left: 10px;
     margin-right: 10px;
   };
   .right {
     float: right;
   }
  </style>
{% endblock %}
{% block activenews %}active{% endblock %}
{% block content %}
  <div class="articles">
      <div class="ui divided list">
	{% for item in EQD %}
	  <div class="item">
	      <img class="ui avatar image" src="{{ item.image }}"/>
	      <div class="content">
		<a class="header" href="{% url "pw.views.article" item.id %}">{{ item.title }}</a>
	      </div>
	  </div>
	{% endfor %}
      </div>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load pw_extras %}
{% block title %} Home {% endblock %}
{% block activehome %}active{% endblock %}
{% block content %}
  <div class="ui segment">
    <h2 class="ui header">Hi !</h2>
    <p>Welcome to PonyWeb, a web reader.</p>
    <p>This is the first version, but you can already do a few things. Like see RSS feeds. Or watch some artworks, read stories, so on and so forth.</p>
    <p>If you wish to add a specific website to the ones supported by PonyWeb, or add a feature, please feel free to contact me, and I'll see what I can do. My profile is here :  {{ "CoiledSpring"|userize }}.</p>
  </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}Log in{% endblock %}
{% block activelogin %}active{% endblock %}
{% block style %}
	<style>
	#form-div {
		margin-right: 15%;
		margin-left: 15%;
	}
	</style>
{% endblock %}
{% block content %}
	{% if error %}
		<div class="ui negative message" id="form-div">
			<div class="header">
				This user account does not exist, or the password is incorrect.
			</div>
		</div>
	{% endif %}
	{% if user.is_authenticated %}

	{% else %}
		<div class="ui segment two column middle aligned stackable grid" id="form-div">
			<div class="column">
				<form method="post" action="/login{% if next %}?next={{ next }}{% endif %}" class="ui form" >
					{% csrf_token %}
					<div class="required field">
						<label>Username</label>
						<div class="ui icon input">
							<input id="id_username" maxlength="30" name="username" type="text" placeholder="Username"/>
							<i class="icon user"></i>
						</div>
					</div>
					<div class="required field">
						<label>Password</label>
						<div class="ui icon input">
							<input id="id_password" name="password" type="password" placeholder="Password"/>
							<i class="lock icon"></i>
						</div>
					</div>
					<input type="submit" value="Login" class="ui submit button"/>
				</form>
			</div>
			<div class="ui vertical divider">OR</div>
			<div class="center aligned column">
				<a href="/signup">
					<div class="huge green ui labeled icon button">
						<i class="signup icon"></i>
						Sign Up
					</div>
				</a>
			</div>
		</div>
	{% endif %}
{% endblock %}

templates/menu.html
{% block mode %}
  
{% endblock %}

templates/modify_account.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Modify your Account" %}{% endblock %}
{% block style %}
<style>
#main-div {
	margin-right: 20%;
	margin-left : 20%;
}
</style>
{% endblock %}
{% block content %}
<div id="main-div">
	{% if error == "bad_password" %}
	<div class="ui warning message">
		<div class="header">{% trans "Bad password !" %}</div>
		<div class="content">{% trans "The password you entered is incorrect." %}</div>
	</div>
	{% elif error == "no_password" %}
	<div class="ui warning message">
		<div class="header">No password !</div>
		<div class="content">{% trans "You <u>must</u> enter your current password in order to modify your account." %}</div>
	</div>
	{% elif error == "different_passwords" %}
	<div class="ui warning message">
		<div class="header">{% trans "Different passwords" %}</div>
		<div class="content">{% trans "The two passwords fields must be identical" %}</div>
	</div>
	{% elif error == "none" %}
	<div class="ui positive message">
		<div class="header">{% trans "Success" %}</div>
		<div class="content">{% trans "Your infos have been modified." %}</div>
	</div>
	{% endif %}
	<div class="ui segment">
		<div class="ui dividing header">{% trans "Modify your Account" %}</div>
		<form class="ui form" action="/account/" method="post">
			{% csrf_token %}
			<div class="two fields">
				<div class="field">
					<label>{% trans "First name" %}</label>
					<input name="first_name" placeholder='{% trans "First name" %}' value="{{ request.user.first_name }}">
				</div>
				<div class="field">
					<label>{% trans "Last name" %}</label>
					<input name="last_name" placeholder='{% trans "Last name" %}' value="{{ request.user.last_name }}">
				</div>
			</div>
			<div class="field">
				<label>{% trans "Gender" %}</label>
				<div class="ui selection dropdown">
					<input name="gender" type="hidden" value={{ profile.gender }}>
					<div class="default text">{% trans "Gender" %}</div>
					<i class="dropdown icon"></i>
					<div class="menu">
						<div class="item" data-value=1><i class="icon woman"></i>{% trans "Woman" %}</div>
						<div class="item" data-value=3><i class="icon man"></i>{% trans "Man" %}</div>
						<div class="item" data-value=0><i class="icon neuter"></i>{% trans "Other" %}</div>
						<div class="item" data-value=5><i class="icon remove"></i>{% trans "I don't want to say it." %}</div>
					</div>
				</div>
			</div>
			<div class="field">
				<label>{% trans "Twitter account" %}</label>
				<div class="ui labeled icon input">
					<div class="ui label">@</div>
					<input name="twitter" placeholder='{% trans "Twitter account" %}' value="{{profile.twitter}}">
					<i class="icon twitter"></i>
				</div>
			</div>
			<div class="two fields">
				<div class="field">
					<label>{% trans "New password" %}</label>
					<div class="ui icon input">
						<input type="password" name="new_password" placeholder='{% trans "New password" %}'>
						<i class="icon lock"></i>
					</div>
				</div>
				<div class="field">
					<label>{% trans "Repeat the new password" %}</label>
					<div class="ui icon input">
						<input type="password" name="new_password2" placeholder='{% trans "New password … again" %}'>
						<i class="icon lock"></i>
					</div>
				</div>
			</div>
			<div class="ui divider"></div>
			<div class="field">
				<label>{% trans "Current password" %}</label>
				<div class="ui icon input">
					<input type="password" name="password" placeholder='{% trans "Current Password" %}'>
					<i class="icon lock"></i>
				</div>
			</div>
			<input type="submit" value='{% trans "Submit" %}' class="ui submit button" />
		</form>
	</div>
	<div class="ui segment">
		<div class="ui dividing header">{% trans "Change language" %}</div>
		<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
			<input name="next" type="hidden" value="{{ redirect_to }}" />
			<select name="language">
				{% get_current_language as LANGUAGE_CODE %}
				{% get_available_languages as LANGUAGES %}
				{% get_language_info_list for LANGUAGES as languages %}
				{% for language in languages %}
				<option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
					{{ language.name_local }} ({{ language.code }})
				</option>
				{% endfor %}
			</select>
			<input type="submit" value="Go" />
		</form>
	</div>
</div>
{% endblock %}
{% block script %}
<script>
window.onload = function() {
	$('.dropdown').dropdown({transition: 'fade up'});
	$('.ui.checkbox').checkbox();
}
</script>
{% endblock %}

templates/news.html
{% extends 'base.html' %}
{% block title %}News{% endblock %}
{% block secondarymenu %}
	<div class="ui secondary pointing menu fluid">
		<a class="item {% if submode == "home" %}active{% endif %}" {% if submode != "home" %}href="/news"{% endif %}>
			<i class="icon home"></i>Home
		</a>
		<a class="item {% if submode == "subscriptions" %}active{% endif %}" {% if submode != "subscriptions" %}href="/news/subscriptions"{% endif %}>
			<i class="icon inbox"></i>My Subscriptions
		</a>
		<div class="right menu">
			<a class="right item {% if submode == "write" %}active{% endif %}" {% if submode != "write" %}href="/news/write"{% endif %}>
				<i class="icon write"></i>Write a News
			</a>
		</div>
	</div>
{% endblock %}

templates/news_home.html
{% extends 'news.html' %}
{% block app %}ng-app="News"{% endblock %}
{% block content %}
	<div class="ui items" ng-controller="NewsController as news">
		<div class="item">
			<div class="content">
				<a class="header">Your Latest News</a>

			</div>
		</div>
		<div class="item">
			<div class="content">
				<a class="header">The Latest News</a>
			</div>
		</div>
	</div>
{% endblock %}
{% block scripthead %}
	<script src="/dist/js/news.js"></script>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Sign up{% endblock %}
{% block activesignup %}active{% endblock %}
{% block style %}
	<style>
	#taille {
		margin-right: 20%;
		margin-left:  20%;
	}
	</style>
{% endblock %}
{% block content %}
	{% if error %}
		<div class="ui warning message" id="taille">
			{% blocktrans %}Either this username is already taken, or the passwords aren't the same.{% endblocktrans %}
		</div>
	{% endif %}
	<div class="ui segment" id="taille">
		<h1 class="ui center aligned dividing header">{% trans "Sign up" %}</h1>
		<form method="post" action="/signup" class="ui form" >
			{% csrf_token %}
			<div class="two fields">
				<div class="required field">
					<label>{% trans "Username" %}</label>
					<div class="ui icon input">
						<input maxlength="30" name="username" type="text" placeholder='{% trans "Username"}'/>
						<i class="icon user"></i>
					</div>
				</div>
				<div class="field">
					<div class="two fields">
						<div class="field">
							<label>{% trans "First name" %}</label>
							<input id="id_first_name" name="first_name" type="text" placeholder='{% trans "First name" %}'>
						</div>
						<div class="field">
							<label>{% trans "Last name" %}</label>
							<input id="id_last_name" name="last_name" type="text" placeholder='{% trans "Last name" %}'>
						</div>
					</div>
				</div>
			</div>
			<div class="required field">
				<label>{% trans "Email adress" %}</label>
				<div class="ui input icon">
					<input name="email" type="text" placeholder='{% trans "Email adress" %}'>
					<i class="mail icon"></i>
				</div>
			</div>
			<div class="field">
				<label>{% trans "Gender" %}</label>
				<div class="ui selection dropdown">
					<input name="gender" type="hidden">
					<div class="default text">{% trans "Gender" %}</div>
					<i class="dropdown icon"></i>
					<div class="menu">
						<div class="item" data-value="man"><i class="icon man"></i>{% trans "Man" %}</div>
						<div class="item" data-value="woman"><i class="icon woman"></i>{% trans "Woman" %}</div>
						<div class="item" data-value="inter"><i class="icon intergender"></i>{% trans "Other" %}</div>
						<div class="item" data-value="none"><i class="icon remove"></i>{% trans "I don't want to say it." %}</div>
					</div>
				</div>
			</div>
			<div class="two fields">
				<div class="required field">
					<label>{% trans "Password" %}</label>
					<div class="ui icon input">
						<input id="id_password1" name="password1" type="password" placeholder='{% trans "Password" %}'>
						<i class="icon lock"></i>
					</div>
				</div>
				<div class="required field">
					<label>{% trans "Repeat password" %}</label>
					<div class="ui icon input">
						<input id="id_password2" name="password2" type="password" placeholder='{% trans "Password… again" %}'>
						<i class="icon lock"></i>
					</div>
				</div>
			</div>
			<div class="field">
				<div class="ui checkbox">
					<input id="id_terms" name="terms" type="checkbox">
					<label>{% blocktrans %}I agree to the <a href="/tos">Terms of Service</a>{% endblocktrans %}</label>
				</div>
			</div>
			<div class="ui submit button">{% trans "Sign up" %}</div>
		</form>
	</div>
{% endblock %}
{% block script %}
	<script>
	window.onload = function() {
		$('.dropdown').dropdown({transition: 'fade up'});
		$('.ui.checkbox').checkbox();
		$('.ui.form').form({
			username: {
				identifier:"username",
				rules: [{
					type: 'empty',
					prompt:"Please enter a username"
				}]},
			email: {
				identifier:"email",
				rules: [{
					type: 'empty',
					prompt:"Please enter your email"
				},{
					type: 'email',
					prompt:"Please enter a correct email address."
				}]},
			gender: {
				identifier:"gender",
				rules: [{
					type: "empty",
					prompt:"Please fill this field"
				}]
			},
			password1: {
				identifier:"password1",
				rules: [{
					type: 'empty',
					prompt:"Please enter a password"
				}]},
			password2: {
				identifier:"password2",
				rules: [{
					type: 'empty',
					prompt:"This field needs to be filled."
				},{
					type: 'match[password1]',
					prompt:"The two passwords field don't match"
				}]},
			terms: {
				identifier:"terms",
				rules: [{
					type:"checked",
					prompt:"You need to accept the Terms."
				}]}
			});
	};
	</script>
{% endblock %}

templates/subscriptions.html
{% extends 'news.html' %}
{% block title %}My Subscriptions{% endblock %}

templates/tos.html
{% extends 'base.html' %}
{% block title %}Terms of Service{% endblock %}
{% block style %}
	<style>
	#taille {
		margin-right: 20%;
		margin-left:  20%;
	}
	</style>
{% endblock %}
{% block content %}
	<div class="ui segment" id="taille">
		<h1 class="ui center aligned dividing header">Terms of Service</h1>
		<div class="ui ordered list">
			<div class="item">You shall not use this service to blow up France. Or another country. But particulary France.</div>
			<div class="item">You shall not kill any member of the staff.</div>
			<div class="item">You shall not pass.</div>
		</div>
		<div>
			If you respect all these points, you'll probably be fine.
		</div>
	</div>
{% endblock %}

templates/view_account.html
{% extends 'base.html' %}
{% load pw_extras %}
{% load humanize %}
{% block style %}
	<style>
	@media screen and (max-width: 767px){

	}
	@media screen and (min-width: 767px){
		#main-div {
			margin-right: 20%;
			margin-left:  20%;
		}
	}
	</style>
{% endblock %}
{% block title %}
	{% if notfound %}Not found
	{% else %}{{ profile.user.username }}
	{% endif %}
{% endblock %}
{% block addmenu %}
	{% if mode != "self" %}
		<div class="ui item active">
			<i class="ui icon user"></i>{{ profile.user.username }}
		</div>
	{% endif %}
{% endblock %}
{% block content %}
	{% if notfound %}
		<div class="ui segment" id="main-div">
			<div class="ui dividing header">Not found</div>
			This user does not exist.
		</div>
	{% else %}
		<div id="main-div">
			<div class="ui segment">
				<div class="ui dividing header">
					{{ profile.user.username }}
					<div class="ui tiny button right floated">Follow</div>
				</div>
				Name: {{ profile.user.first_name }} {{ profile.user.last_name }}<br />
				Gender: <i class="icon {% if profile.gender == 0 %}neuter{% elif profile.gender == 1 %}woman{% elif profile.gender == 2 %}man{% elif profile.gender == 3 %}remove{% endif %}"></i><br />
				Joined: {{ profile.user.date_joined|naturalday:"DATE_FORMAT" }}<br />
				Last connected: {{profile.user.last_login|naturaltime}}<br/>
				{% if profile.presentation %}
					Presentation: {{ profile.presentation }}<br />
				{% endif %}
				How you can find them : <br />
				{% if profile.twitter != "" %}
					<i class="icon twitter"></i>{{ profile.twitter|twitterize }}<br />
				{% else %}
					Not on Twitter :-(
				{% endif %}
				{% if profile.show_mail %}
					<i class="icon mail"></i>{{ profile.user.email|urlize }}<br />
				{% else %}
					You cannot send them mail :-(
				{% endif %}
			</div>
			<div class="ui segment">
				<div class="ui dividing header">Newers they follow</div>
				{% for i in following_news %}
					{{ i.user.username|userize }}<br />
				{% endfor %}
			</div>

		</div>
	{% endif %}
{% endblock %}

templates/view_news.html
{% extends 'base.html' %}
{% load pw_extras %}
{% block title %}{{ news.title }}{% endblock %}
{% block content %}
	<h2 class="ui dividing header">{{ news.title }}<div class="sub header"> by {{ news.author|userize }}</div></h2>
	{% autoescape off %}
		{{ news.content }}
	{% endautoescape %}
{% endblock %}